modLoader="javafml"
loaderVersion="[2,)"
license="MIT License https://github.com/McJtyMods/XNet/blob/1.21_neo/LICENCE"
issueTrackerURL="http://github.com/McJtyMods/XNet/issues"
displayURL="http://github.com/McJtyMods/XNet/"
#logoFile="examplemod.png" #optional
#credits="Thanks for this example mod goes to Java" #optional
authors="McJty"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[mods]]
modId="xnet"
version="${file.jarVersion}"
displayName="XNet"
#updateJSONURL="http://myurl.me/" #optional
description='''
Powerful item/fluid/energy transfer
'''
[[dependencies.xnet]]
    modId="neoforge"
    mandatory=true
    versionRange="[21.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.xnet]]
    modId="mcjtylib"
    mandatory=true
    versionRange="[1.21-9.0.0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.xnet]]
    modId="rftoolsbase"
    mandatory=true
    versionRange="[1.21-6.0.0,)"
    ordering="AFTER"
    side="BOTH"